apiVersion: v1
kind: ConfigMap
metadata:
  name: evo
  labels:
    app: nginx-evo
    chart: nginx-evo-0.1.2
    heritage: Tiller
    release: evo
data:
  evo.conf : {{.Files.Get "conf/evo.conf" | printf "%s" | indent 4 }}
