apiVersion: v1
kind: ConfigMap
metadata:
  name: upstream
  labels:
    app: nginx-evo
    chart: nginx-evo-0.1.2
    heritage: Tiller
    release: evo
data:
  upstream.conf : {{.Files.Get "conf/upstream.conf" | printf "%s" | indent 4 }}
