apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-main-config
  labels:
    app: {{ template "nginx-evo.name" . }}
    chart: {{ template "nginx-evo.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  nginx.conf: |-
    user  root;
    worker_processes auto;
    worker_rlimit_nofile 16384;

    worker_shutdown_timeout 10s ;

    load_module modules/ngx_http_opentracing_module.so;

    daemon off;

    events {
        worker_connections 51200;
        use epoll;
        multi_accept        on;
    }

    http {

        include       mime.types;
        default_type  application/octet-stream;

        log_format  main  '{"@timestamp":"$time_iso8601",'
                    '"client_ip":"$remote_addr",'
                    '"request_protocol":"$server_protocol",'
                    '"request_method":"$request_method",'
                    '"request_address":"$scheme://$server_name:$server_port$request_uri",'
                    '"request_args":"$args",'
                    '"client_cookie":"$http_cookie",'
                    '"request_status":"$status",'
                    '"request_length":"$request_length",'
                    '"request_bytes":"$bytes_sent",'
                    '"request_time":"$request_time",'
                    '"upstream_addr":"$upstream_addr",'
                    '"upstream_response_time":"$upstream_response_time",'
                    '"upstream_status":"$upstream_status",'
                    '"user_agent":"$http_user_agent"}';
  
        access_log  log/access.log  main;
        error_log log/error.log debug;

        sendfile            on;
        proxy_buffering off;
        client_max_body_size  2000m;
        server_names_hash_bucket_size 128;
        proxy_max_temp_file_size 128m;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        opentracing on;
        opentracing_load_tracer /usr/local/nginx/modules/libjaegertracing_plugin.linux_amd64.so /usr/local/nginx/conf/jaeger-config.json;
        opentracing_propagate_context;
        opentracing_operation_name $host$uri;
        opentracing_tag request.id $request_id;

        gzip  on;
        gzip_min_length  5k;
        gzip_buffers     4 16k;
        gzip_comp_level 3;
        gzip_types       text/plain application/x-javascript text/css application/xml application/json text/javascript application/x-httpd-php image/jpeg image/gif image/png;
        gzip_vary on;

        include /usr/local/nginx/conf.d/upstream.conf;

        server {

            listen {{ .Values.server.Port }};
            server_name {{ .Values.server.Host }};


            location = /_ping {
                auth_basic off;
                root   /usr/share/nginx/html;
                stub_status on;
            }

            include /usr/local/nginx/conf.d/evo.conf;
        }
    }
