apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo.name" . }}
    helm.sh/chart: {{ include "demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.containerPort.port1 }}
      targetPort: {{ .Values.containerPort.port1 }}
      protocol: TCP
      name: http-{{ .Values.containerPort.port1 }}
    - port: {{ .Values.containerPort.port2 }}
      targetPort: {{ .Values.containerPort.port2 }}
      protocol: TCP
      name: http-{{ .Values.containerPort.port2 }}
    - port: {{ .Values.containerPort.port3 }}
      targetPort: {{ .Values.containerPort.port3 }}
      protocol: TCP
      name: http-{{ .Values.containerPort.port3 }}
  selector:
    app.kubernetes.io/name: {{ include "demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
