apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-main-config
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      scrape_timeout: 5s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: eureka-discovery
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /actuator/prometheus
        consul_sd_configs:
        - server: registry:8761
          tag_separator: ','
          allow_stale: true
          refresh_interval: 30s
          services: []
        relabel_configs:
        - source_labels: [__meta_consul_service]
          separator: ;
          regex: (.*)
          target_label: application
          replacement: ${1}
          action: replace
        - source_labels: [__meta_consul_metadata_metrics_path]
          separator: ;
          regex: (.*)
          target_label: __metrics_path__
          replacement: ${1}
          action: replace
        - source_labels: [__address__]
          separator: ;
          regex: (.*)
          target_label: instance
          replacement: ${1}
          action: replace
