apiVersion: v1
kind: ConfigMap
metadata:
  name: register-erika-config-{{ include "demo.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo.name" . }}
    helm.sh/chart: {{ include "demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  evo-prefer-ip: "true"
  evo-wes-ip: "{{ .Values.configMap.host_ip }}"
  evo-wes-port: "{{ .Values.configMap.host_port }}"
