apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  generation: 38
  labels:
    app.kubernetes.io/instance: deploy-1577265051-evo-basic
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: evo-basic
    helm.sh/chart: evo-basic-0.0.292
  name: evo-basic
  namespace: deploy-1577265051
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: deploy-1577265051-evo-basic
      app.kubernetes.io/name: evo-basic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: deploy-1577265051-evo-basic
        app.kubernetes.io/name: evo-basic
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: db.url
          value: mysql:3306
        - name: db.username
          value: root
        - name: db.password
          value: "123456"
        - name: registry
          value: registry:8761
        - name: host.ip
          value: 172.31.238.15
        - name: host.port
          value: '32498'
        - name: redis.host
          value: redis
        - name: release.name
          value: evo-basic
        - name: rmqnamesrv
          value: rmq:9876
        image: harbor2.flashhold.com/evo-baseapp/evo-basic:p2-optimization-19122802
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/info
            port: 8023
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: evo-basic
        ports:
        - containerPort: 8023
          name: http-8023
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z registry 8761 ; do echo waiting for registry; sleep 2; done;
        image: harbor2.flashhold.com/library/busybox:latest
        imagePullPolicy: Always
        name: dependency
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        kubernetes.io/hostname: knode3.local
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
