apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ include "rdp.name" . }}
    helm.sh/chart: {{ include "rdp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rdp.port }}
      targetPort: http-rdp
      protocol: TCP
      name: http-rdp
    - port: {{ .Values.service.etl.port }}
      targetPort: http-etl
      protocol: TCP
      name: http-etl
  selector:
    app.kubernetes.io/name: {{ include "rdp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
